# Generated by Django 4.1 on 2024-05-13 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musician',
            old_name='date_of_applyinng',
            new_name='date_of_applying',
        ),
    ]
